<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title> &raquo; Armours 3k | Darling Disaster</title>
<link href="http://3k.darlingdisaster.com/wp-content/themes/koi/style.css" rel="stylesheet" type="text/css" />
<link rel="pingback" href="http://3k.darlingdisaster.com/xmlrpc.php" />
<script src="/sorttable.js"></script>
<link rel="alternate" type="application/rss+xml" title="3k | Darling Disaster &raquo; Feed" href="http://3k.darlingdisaster.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="3k | Darling Disaster &raquo; Comments Feed" href="http://3k.darlingdisaster.com/comments/feed/" />
<link rel="alternate" type="application/rss+xml" title="3k | Darling Disaster &raquo; Armours Comments Feed" href="http://3k.darlingdisaster.com/armours/feed/" />
<link rel='stylesheet' id='sharedaddy-css'  href='http://3k.darlingdisaster.com/wp-content/plugins/jetpack/modules/sharedaddy/sharing.css?ver=3.2.1' type='text/css' media='all' />
<script type='text/javascript' src='http://3k.darlingdisaster.com/wp-includes/js/l10n.js?ver=20101110'></script>
<script type='text/javascript' src='http://3k.darlingdisaster.com/wp-includes/js/comment-reply.js?ver=20090102'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://3k.darlingdisaster.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://3k.darlingdisaster.com/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='3k | Darling Disaster' href='http://3k.darlingdisaster.com/' />
<link rel='next' title='Weapons' href='http://3k.darlingdisaster.com/weapons/' />
<meta name="generator" content="WordPress 3.2.1" />
<link rel='canonical' href='http://3k.darlingdisaster.com/armours/' />
<link rel='shortlink' href='http://wp.me/P1K7mx-7' />
	<style type="text/css">
				#header #logo, #header #logo a, #header #description {
			color: #6c5c46;
		}
		</style>
</head>
<body class="page page-id-7 page-parent page-template-default">
<div id="wrapper">
<div id="header">
	<h1 id="logo"><a href="http://3k.darlingdisaster.com/">3k | Darling Disaster</a></h1>
	<p id="description">Parisienne&#039;s 3Kingdoms page</p>

	
	<div id="nav">
		<ul class="menu page-menu">
	<li class="page_item "><a href="http://3k.darlingdisaster.com/">Home</a></li>
	<li class="page_item page-item-7"><a href="http://3k.darlingdisaster.com/armours/" title="Armours">Armours</a>
<ul class='children'>
	<li class="page_item page-item-60"><a href="http://3k.darlingdisaster.com/armours/helmets/" title="Helmets">Helmets</a></li>
	<li class="page_item page-item-63"><a href="http://3k.darlingdisaster.com/armours/amulets/" title="Amulets">Amulets</a></li>
	<li class="page_item page-item-65"><a href="http://3k.darlingdisaster.com/armours/mains/" title="Mains">Mains</a></li>
	<li class="page_item page-item-67"><a href="http://3k.darlingdisaster.com/armours/breastplates/" title="Breastplates">Breastplates</a></li>
	<li class="page_item page-item-69"><a href="http://3k.darlingdisaster.com/armours/greaves/" title="Greaves">Greaves</a></li>
	<li class="page_item page-item-71"><a href="http://3k.darlingdisaster.com/armours/gloves/" title="Gloves">Gloves</a></li>
	<li class="page_item page-item-73"><a href="http://3k.darlingdisaster.com/armours/boots/" title="Boots">Boots</a></li>
	<li class="page_item page-item-75"><a href="http://3k.darlingdisaster.com/armours/rings/" title="Rings">Rings</a></li>
	<li class="page_item page-item-77"><a href="http://3k.darlingdisaster.com/armours/shields/" title="Shields">Shields</a></li>
	<li class="page_item page-item-79"><a href="http://3k.darlingdisaster.com/armours/others/" title="Others">Others</a></li>
	<li class="page_item page-item-51"><a href="http://3k.darlingdisaster.com/armours/edit/" title="Add Armour">Add Armour</a></li>
</ul>
</li>
<li class="page_item page-item-10"><a href="http://3k.darlingdisaster.com/weapons/" title="Weapons">Weapons</a>
<ul class='children'>
	<li class="page_item page-item-99"><a href="http://3k.darlingdisaster.com/weapons/add-weapon/" title="Add Weapon">Add Weapon</a></li>
</ul>
</li>
<li class="page_item page-item-12"><a href="http://3k.darlingdisaster.com/tinyfugue/" title="Tinyfugue">Tinyfugue</a></li>
<li class="page_item page-item-14"><a href="http://3k.darlingdisaster.com/tips/" title="Tips">Tips</a></li>
</ul>
	</div>

		<form method="get" id="searchform" action="http://3k.darlingdisaster.com/">
		<input type="text" value="Search..." name="s" id="s" onblur="if (this.value == '') {this.value = 'Search...';}" onfocus="if (this.value == 'Search...') { this.value = ''; }" />
		<input type="submit" value="Search" id="searchsubmit" />
	</form></div>
<!--/header -->
	<div id="content">

	
		<div class="post-7 page type-page status-publish hentry">
			